site_name: Gamedev for beginners
theme:
  name: material
nav:
  - Home: index.md
  - Unity package installation: installation/unity_upm_installation.md
  - Interactive documentation: installation/unity_interactive_documentation.md
  - Gamedev:
      - World: game_dev/world/world.md
        - Barriers: game_dev/world/world_barriers.md
        - Terrain: game_dev/world/world_terrain.md
        - Biomes: game_dev/world/world_biomes.md
        - Landmarks: game_dev/world/world_landmarks.md
        - Blocking: game_dev/world/world_design_blocking.md
        - Tools: game_dev/world/world_design_tools.md
        - Level design: game_dev/world/world_level_design.md
      - building blocks:
        - Camera: game_dev/building_blocks/camera.md
        - Character controller: game_dev/building_blocks/character_controller.md
        - World: game_dev/building_blocks/world.md
        - Console: game_dev/building_blocks/console.md
        - Triggers: game_dev/building_blocks/triggers.md
        - Teleports: game_dev/building_blocks/teleports.md
        - Timers: game_dev/building_blocks/timers.md
        - Spawners: game_dev/building_blocks/spawners.md
        - Counters: game_dev/building_blocks/counters.md
        - Quests: game_dev/building_blocks/quests.md
        - Inventory: game_dev/building_blocks/inventory.md
        - Map: game_dev/building_blocks/map.md
        - Chance: game_dev/building_blocks/chance.md